# Logo
favicon = "images/favicon.png"
logo_desktop = "images/logo.png"
logo_desktop_width = "230px"
logo_mobile = "images/logo-mobile.png"
logo_mobile_width = "100px"

# meta description
author = "Themefisher"
description = "Documentation for the installation and configuration of our themes."
topic_title = "Theme Documentations"
# google site verification
google_verification = "hJdPvFvxl7QE_iYAxYyAxvdEh5Ar_Kqofcj7ySaWlMY"
# premium badge
premium_badge = true
# search
search = true
# preloader
preloader = true
feedback_action = "" # https://airform.io/mehedi@gethugothemes.com
edit_page_url = "https://github.com/gethugothemes/documentation/edit/master/content/"
copyright = "This website is powered by our own [Godocs Theme](https://gethugothemes.com/products/godocs-hugo-documentation-theme/)"

# custom script
custom_script= "<script>!function(t,e,n){function s(){const t=e.getElementsByTagName('script')[0],n=e.createElement('script');n.type='text/javascript',n.async=!0,n.src='https://assistant.thrivedesk.io/bootloader.js?'+Date.now(),t.parentNode.insertBefore(n,t)}if(t.Assistant=n=function(e,n,s){t.Assistant.readyQueue.push({method:e,options:n,data:s})},n.readyQueue=[],'complete'===e.readyState)return s();t.attachEvent?t.attachEvent('onload',s):t.addEventListener('load',s,!1)}(window,document,window.Assistant||function(){}),window.Assistant('init','9416737f-790d-4d29-bdab-9fb279b86962');</script>"

[banner]
image = "images/banner.jpg"
subtitle = "We are the biggest hugo theme provider in the market , We will cover all our themes installation documentation here . "
title = "Welcome to Gethugothemes"

[call_to_action]
enable = true
title = "Could not find what you were looking for?"
content = "Feel free to contact us any time to submit your questions or suggestions. You will receive priority support if you are using our premium products."
image = "images/cta-illustration.jpg"
[call_to_action.button]
enable = true
label = "Start a conversation now!"
link = ""
attribute = "onclick=Assistant('open')"

[navigation_button_bordered]
enable = true
label = "Contact Us"
link = "https://gethugothemes.com/contact/"
attribute = ""

[promotion]
enable = false
title = "Still Having Problems??"
content = "No problem mate, we offer custom service. Feel free to contact us."
button_label = "Contact Us"
button_link = "mailto:mehedi@themefisher.com"

[navigation_button_solid]
enable = true
label = "guide"
link = "guide"
attribute = ""